from manim import *

TAG_COLOR = BLUE
INDEX_COLOR = GREEN
OFFSET_COLOR = RED

VALID_COLOR = YELLOW
DATA_COLOR = PURPLE
COMPARATOR_COLOR = WHITE
TEXT_COLOR = WHITE
PARAM_COLOR = YELLOW_B

# Font-size scale
FS_TITLE   = 28
FS_SECTION = 22
FS_BODY    = 18
FS_SMALL   = 14

ADDRESS_HEIGHT = 1.0
ADDRESS_WIDTH = 10.0
TABLE_SCALE = 0.8

TAG_BITS = 18
INDEX_BITS = 10
OFFSET_BITS = 4
TOTAL_BITS = 32
